CREATE TABLE [dbo].[Captain]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  [Name] NVARCHAR(256) NOT NULL,
  [Rank] NVARCHAR(256) NOT NULL,
  [HomePlanet] NVARCHAR(256) NULL,
  [Born] DATETIME2 NOT NULL,
  [Died] DATETIME2 NULL,
  [CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Captain_CreatedAt DEFAULT (GETUTCDATE()),
  [LastUpdatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Captain_LastUpdatedAt DEFAULT (GETUTCDATE())
)
