CREATE TABLE [dbo].[Faction]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [Name] NVARCHAR(1024) NOT NULL,
  [Colour] NVARCHAR(256) NULL,
  [CreatedAt] DATETIME2 NOT NULL DEFAULT DF_Faction_CreatedAt(GETUTUCDATE()),
  [LastUpdatedAt] DATETIME2 NOT NULL DEFAULT DF_Faction_LastUpdatedAt(GETUTCDATE())
)
