CREATE TABLE [dbo].[Faction]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [Name] NVARCHAR(1024) NOT NULL,
  [Colour] NVARCHAR(256) NULL,
  [CreatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Faction_CreatedAt DEFAULT (GETUTCDATE()),
  [LastUpdatedAt] DATETIME2 NOT NULL CONSTRAINT DF_Faction_LastUpdatedAt DEFAULT (GETUTCDATE())
)
